apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-09-10T21:24:31Z"
  generation: 1
  labels:
    app: test-app-summon-sidecar
  name: test-app-summon-sidecar
  namespace: test-app
  resourceVersion: "12727751"
  selfLink: /apis/apps/v1/namespaces/test-app/deployments/test-app-summon-sidecar
  uid: a5900ce0-230c-4202-8619-8023b9753688
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app-summon-sidecar
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app-summon-sidecar
    spec:
      containers:
      - env:
        - name: CONJUR_APPLIANCE_URL
          value: https://conjur-follower.conjur-follower.svc.cluster.local/api
        - name: CONJUR_ACCOUNT
          value: deloittepilot
        - name: CONJUR_AUTHN_TOKEN_FILE
          value: /run/conjur/access-token
        - name: CONJUR_SSL_CERTIFICATE
          valueFrom:
            configMapKeyRef:
              key: ssl-certificate
              name: test-app
        image: 080097767956.dkr.ecr.ap-southeast-2.amazonaws.com/conjur-follower/test-sidecar-app:conjur-follower
        imagePullPolicy: Always
        name: test-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /pets
            port: http
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/conjur
          name: conjur-access-token
          readOnly: true
      - env:
        - name: CONTAINER_MODE
          value: sidecar
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CONJUR_AUTHN_URL
          value: https://conjur-follower.conjur-follower.svc.cluster.local/api/authn-k8s/conjur-authenticator
        - name: CONJUR_ACCOUNT
          value: deloittepilot
        - name: CONJUR_AUTHN_LOGIN
          value: host/conjur/authn-k8s/conjur-authenticator/apps/test-app/deployment/test-app-summon-sidecar
        - name: CONJUR_SSL_CERTIFICATE
          valueFrom:
            configMapKeyRef:
              key: ssl-certificate
              name: test-app
        image: cyberark/conjur-authn-k8s-client
        imagePullPolicy: Always
        name: authenticator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/conjur
          name: conjur-access-token
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerpullsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: test-app-summon-sidecar
      serviceAccountName: test-app-summon-sidecar
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: conjur-access-token
status:
  conditions:
  - lastTransitionTime: "2020-09-10T21:24:31Z"
    lastUpdateTime: "2020-09-10T21:24:31Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-09-10T21:34:32Z"
    lastUpdateTime: "2020-09-10T21:34:32Z"
    message: ReplicaSet "test-app-summon-sidecar-5d9cd79d47" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

